# Generated by Django 6.1 on 2026-08-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsmodel",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products"),
        ),
    ]
